name: Deploy Next JS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: git-github-practice/21-job-currnency/next-app

      - name: Build Next.js App
        run: npm run build
        working-directory: git-github-practice/21-job-currnency/next-app

      - name: Deploy App
        run: echo "Deploying App"
