name: Next JS Build with Caching and Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: git-github-practice/20-nextjs-build-artifact-caching/next-app/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: git-github-practice/20-nextjs-build-artifact-caching/next-app

      - name: Build Next.js App
        run: npm run build
        working-directory: git-github-practice/20-nextjs-build-artifact-caching/next-app


      - name: Show Build Files
        run: ls -la
        working-directory: git-github-practice/20-nextjs-build-artifact-caching/next-app

      - name: Print Current Directory
        run: pwd


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: git-github-practice/20-nextjs-build-artifact-caching/next-app/
